spring:
  application:
    name: spring-cloud-producer
server:
  port: 9002

#\u4F7F\u7528eureka,\u53E6\u5916\u9700\u8981\u4E00\u4E2A\u5E94\u7528\u4F5C\u4E3A\u670D\u52A1\u6CE8\u518C\u4E2D\u5FC3
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
    #\u662F\u5426\u6CE8\u518C\u670D\u52A1
    #register-with-eureka: false