spring:
  application:
    name: spring-cloud-producer
server:
  port: 9002

#eureka服务配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
    #不注册该服务
    #register-with-eureka: false